spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/products"
        username: "bapun"
        password: "malik@123"
    jpa:
        hibernate: 
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

project:
    poster: poster/

base:
    url: "http://localhost:8080"
